"""Unit tests for the utilities exceptions module."""

import pytest


class TestCropError:
    """Tests for the CropError exception."""

    @pytest.mark.skip(reason="Placeholder test - to be implemented by developers")
    def test_crop_error(self) -> None:
        """Test the CropError exception."""
        pass

    @pytest.mark.skip(reason="Placeholder test - to be implemented by developers")
    def test_crop_error_custom_message(self) -> None:
        """Test the CropError exception with a custom message."""
        pass


class TestCenterOfRotationError:
    """Tests for the CenterOfRotationError exception."""

    @pytest.mark.skip(reason="Placeholder test - to be implemented by developers")
    def test_center_of_rotation_error(self) -> None:
        """Test the CenterOfRotationError exception."""
        pass

    @pytest.mark.skip(reason="Placeholder test - to be implemented by developers")
    def test_center_of_rotation_error_custom_message(self) -> None:
        """Test the CenterOfRotationError exception with a custom message."""
        pass
